//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 8/11/2015 12:15:01 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Asistencia.DbDominio
{

    /// <summary>
    /// There are no comments for Asistencia.DbDominio.Perfil, Asistencia in the schema.
    /// </summary>
    public partial class Perfil
    {

        #region Extensibility Method Definitions

        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        #endregion
        /// <summary>
        /// There are no comments for Perfil constructor in the schema.
        /// </summary>
        public Perfil()
        {
            this.Habilitado = true;
            this.Activo = true;
            this.Status = true;
            FechaCreacion = DateTime.Now;

            PermisoCatalogoPerfil = false;
            PermisoCatalogoUsuario = false;
            PermisoCatalogoOficina = false;
            PermisoCatalogoEmpleado = false;
            PermisoCatalogoControlAcceso = false;
            PermisoProcesoCargaMasivaEmpleado = false;
            PermisoProcesoCargaMasivaPlantilla = false;
            PermisoProcesoPlantilla = false;
            PermisoProcesoEmpleadoEnControl = false;
            PermisoProcesoCargaPlantillaEnControl = false;
            PermisoProcesoCargaAsistencia = false;
            PermisoProcesoActualizarFechaEnControl = false;
            PermisoReporteAsistencia = false;
            PermisoReporteEmpleadoNoRegistrado = false;

            OnCreated();
        }


        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Nombre in the schema.
        /// </summary>
        public virtual string Nombre
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Descripcion in the schema.
        /// </summary>
        public virtual string Descripcion
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for FechaCreacion in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> FechaCreacion
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for FechaModificacion in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> FechaModificacion
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Status in the schema.
        /// </summary>
        public virtual System.Nullable<bool> Status
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Usuario_creado_por in the schema.
        /// </summary>
        public virtual Usuario Usuario_creado_por
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Usuario_modificado_por in the schema.
        /// </summary>
        public virtual Usuario Usuario_modificado_por
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Habilitado in the schema.
        /// </summary>
        public virtual System.Nullable<bool> Habilitado
        {
            get;
            set;
        }

        /// <summary>
        /// There are no comments for Habilitado in the schema.
        /// </summary>
        public virtual System.Nullable<bool> Activo
        {
            get;
            set;
        }
        public virtual System.Nullable<bool> PermisoCatalogoPerfil { get; set; }
        public virtual System.Nullable<bool> PermisoCatalogoUsuario { get; set; }
        public virtual System.Nullable<bool> PermisoCatalogoOficina { get; set; }
        public virtual System.Nullable<bool> PermisoCatalogoEmpleado { get; set; }
        public virtual System.Nullable<bool> PermisoCatalogoControlAcceso { get; set; }
        public virtual System.Nullable<bool> PermisoProcesoCargaMasivaEmpleado { get; set; }
        public virtual System.Nullable<bool> PermisoProcesoCargaMasivaPlantilla { get; set; }
        public virtual System.Nullable<bool> PermisoProcesoPlantilla { get; set; }
        public virtual System.Nullable<bool> PermisoProcesoEmpleadoEnControl { get; set; }
        public virtual System.Nullable<bool> PermisoProcesoCargaPlantillaEnControl { get; set; }
        public virtual System.Nullable<bool> PermisoProcesoCargaAsistencia { get; set; }
        public virtual System.Nullable<bool> PermisoProcesoActualizarFechaEnControl { get; set; }
        public virtual System.Nullable<bool> PermisoReporteAsistencia { get; set; }
        public virtual System.Nullable<bool> PermisoReporteEmpleadoNoRegistrado { get; set; }
    }

}
