//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 8/11/2015 12:15:01 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Asistencia.DbDominio
{

    /// <summary>
    /// There are no comments for Asistencia.DbDominio.Incidencia, Asistencia in the schema.
    /// </summary>
    public partial class Incidencia
    {

        #region Extensibility Method Definitions

        /**
        public virtual DateTime Version { get; set; }
        public override bool Equals(object obj)
        {
            if (obj == null)
                return false;
            var t = obj as Incidencia;
            if (t == null)
                return false;

            if (CveIncidencia == t.CveIncidencia) {
                return true;
            }
           return false;
        }
        public override int GetHashCode()
        {
            return (Empleado.CveEmpleado + "|" + FechaHoraIncidencia + "|" + ControlAcceso.CveControlAcceso + "|" + InOutMode).GetHashCode();
        }**/

        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        #endregion
        /// <summary>
        /// There are no comments for Incidencia constructor in the schema.
        /// </summary>
        public Incidencia()
        {
            this.EnviadoWs = 0;
            OnCreated();
        }


        /// <summary>
        /// There are no comments for CveIncidencia in the schema.
        /// </summary>
        public virtual int CveIncidencia
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for FechaHoraIncidencia in the schema.
        /// </summary>
        public virtual System.DateTime FechaHoraIncidencia
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for FechaAlta in the schema.
        /// </summary>
        public virtual System.DateTime FechaAlta
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for EnviadoWs in the schema.
        /// </summary>
        public virtual System.Nullable<short> EnviadoWs
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for InOutMode in the schema.
        /// </summary>
        public virtual System.Nullable<int> InOutMode
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Empleado in the schema.
        /// </summary>
        public virtual Empleado Empleado
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Usuario in the schema.
        /// </summary>
        public virtual Usuario Usuario
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for ControlAcceso in the schema.
        /// </summary>
        public virtual ControlAcceso ControlAcceso
        {
            get;
            set;
        }
    }

}
