//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 8/11/2015 12:15:01 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using Asistencia.Clases;

namespace Asistencia.DbDominio
{

    /// <summary>
    /// There are no comments for Asistencia.DbDominio.Oficina, Asistencia in the schema.
    /// </summary>
    public partial class Oficina
    {

        #region Extensibility Method Definitions

        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        #endregion
        /// <summary>
        /// There are no comments for Oficina constructor in the schema.
        /// </summary>
        public Oficina()
        {
            this.Activo = true;
            this.Habilitado = true;
            this.FechaCreacion = DateTime.Now;
            this.FechaModificacion = DateTime.Now;
            OnCreated();
        }

        public virtual string NombreClaseCSS
        {

            get
            {
                return (Activo != null && Activo.Value) ? "css_registro_activo" : "css_registro_inactivo";
            }
        }

        public virtual String NombreZona
        {
            get
            {
                return Zona != null ? Zona.Nombre : Constantes.TEXTO_BLANCO;

            }
        }

        public virtual String NombrePlaza
        {
            get
            {
                return Plaza != null ? Plaza.Nombre : Constantes.TEXTO_BLANCO;

            }
        }


        public virtual String NombreRegion
        {
            get
            {
                return Region != null ? Region.Nombre : Constantes.TEXTO_BLANCO;

            }
        }



        /// <summary>
        /// There are no comments for CveOficina in the schema.
        /// </summary>
        public virtual int CveOficina
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Nombre in the schema.
        /// </summary>
        public virtual string Nombre
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for CodigoPlanta in the schema.
        /// </summary>
        public virtual string CodigoPlanta
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Habilitado in the schema.
        /// </summary>
        public virtual System.Nullable<bool> Habilitado
        {
            get;
            set;
        }

        /// <summary>
        /// There are no comments for Habilitado in the schema.
        /// </summary>
        public virtual System.Nullable<bool> Activo
        {
            get;
            set;
        }

        /// <summary>
        /// There are no comments for FechaCreacion in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> FechaCreacion
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for FechaModificacion in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> FechaModificacion
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for DetalleCatalogo in the schema.
        /// </summary>
        public virtual DetalleCatalogo DetalleCatalogo
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Zona in the schema.
        /// </summary>
        public virtual Zona Zona
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Region in the schema.
        /// </summary>
        public virtual Region Region
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Plaza in the schema.
        /// </summary>
        public virtual Plaza Plaza
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Usuario_creado_por in the schema.
        /// </summary>
        public virtual Usuario Usuario_creado_por
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Usuario_modificado_por in the schema.
        /// </summary>
        public virtual Usuario Usuario_modificado_por
        {
            get;
            set;
        }


    }

}
