//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 8/11/2015 12:15:01 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Asistencia.DbDominio
{

    /// <summary>
    /// There are no comments for Asistencia.DbDominio.ColectorMovimiento, Asistencia in the schema.
    /// </summary>
    public partial class ColectorMovimientoIncidencia
    {

        #region Extensibility Method Definitions

        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        #endregion
        /// <summary>
        /// There are no comments for ColectorMovimiento constructor in the schema.
        /// </summary>
        public ColectorMovimientoIncidencia()
        {
            OnCreated();
            Fecha = DateTime.Now;

        }


        /// <summary>
        /// There are no comments for CveColectorMovimientos in the schema.
        /// </summary>
        public virtual int Id
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for CveServidor in the schema.
        /// </summary>
        public virtual String CveEmpleado
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for CveServidor in the schema.
        /// </summary>
        public virtual String Detalles
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for CveControlAcceso in the schema.
        /// </summary>
        public virtual DateTime Fecha
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for ControlAcceso in the schema.
        /// </summary>
        public virtual ControlAcceso ControlAcceso
        {
            get;
            set;
        }



    }

}
