//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 8/11/2015 12:15:01 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Asistencia.DbDominio
{

    /// <summary>
    /// There are no comments for Asistencia.DbDominio.ColectorMovimiento, Asistencia in the schema.
    /// </summary>
    public partial class ColectorMovimiento
    {

        #region Extensibility Method Definitions

        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        #endregion
        /// <summary>
        /// There are no comments for ColectorMovimiento constructor in the schema.
        /// </summary>
        public ColectorMovimiento()
        {
            OnCreated();
        }

        public ColectorMovimiento(int cveServidor, int cveControlAcceso, string enrollNumber, System.Nullable<int> verifyMode, System.Nullable<int> inOutMode,
             System.Nullable<int> year, System.Nullable<int> month, System.Nullable<int> day, System.Nullable<int> hour, System.Nullable<int> minute, System.Nullable<int> second, System.Nullable<int> workCode)
        {
            CveControlAcceso = cveControlAcceso;
            EnrollNumber = enrollNumber;
            VerifyMode = verifyMode;
            InOutMode = inOutMode;
            Year = year;
            Month = month;
            Day = day;
            Hour = hour;
            Minute = minute;
            Second = second;
            WorkCode = workCode;
        }


        /// <summary>
        /// There are no comments for CveColectorMovimientos in the schema.
        /// </summary>
        public virtual int CveColectorMovimientos
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for CveServidor in the schema.
        /// </summary>
        public virtual int CveServidor
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for CveControlAcceso in the schema.
        /// </summary>
        public virtual int CveControlAcceso
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for EnrollNumber in the schema.
        /// </summary>
        public virtual string EnrollNumber
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for VerifyMode in the schema.
        /// </summary>
        public virtual System.Nullable<int> VerifyMode
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for InOutMode in the schema.
        /// </summary>
        public virtual System.Nullable<int> InOutMode
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Year in the schema.
        /// </summary>
        public virtual System.Nullable<int> Year
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Month in the schema.
        /// </summary>
        public virtual System.Nullable<int> Month
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Day in the schema.
        /// </summary>
        public virtual System.Nullable<int> Day
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Hour in the schema.
        /// </summary>
        public virtual System.Nullable<int> Hour
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Minute in the schema.
        /// </summary>
        public virtual System.Nullable<int> Minute
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Second in the schema.
        /// </summary>
        public virtual System.Nullable<int> Second
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for WorkCode in the schema.
        /// </summary>
        public virtual System.Nullable<int> WorkCode
        {
            get;
            set;
        }



    }

}
