//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 8/11/2015 12:15:01 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using Asistencia.Clases;

namespace Asistencia.DbDominio
{

    /// <summary>
    /// There are no comments for Asistencia.DbDominio.ControlAcceso, Asistencia in the schema.
    /// </summary>
    public partial class ControlAcceso
    {

        #region Extensibility Method Definitions

        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        #endregion
        /// <summary>
        /// There are no comments for ControlAcceso constructor in the schema.
        /// </summary>
        public ControlAcceso()
        {
            Activo = true;
            this.Habilitado = true;
            FechaAlta = DateTime.Now;
            this.FechaModificacion = DateTime.Now;
            IdControl = 0;
            CapacidadHuellas = 10000;
            Puerto = 4730;
            OnCreated();
        }

        public virtual string NombreClaseCSS
        {

            get
            {
                return (Activo != null && Activo.Value) ? "css_registro_activo" : "css_registro_inactivo";
            }
        }

        public virtual String NombreOficina
        {
            get
            {
                return Oficina != null ? Oficina.Nombre : Constantes.TEXTO_BLANCO;

            }
        }

        public virtual String NombrePlaza
        {
            get
            {
                return (Oficina != null && Oficina.Plaza != null) ? Oficina.Plaza.Nombre : Constantes.TEXTO_BLANCO;

            }
        }



        /// <summary>
        /// There are no comments for CveControlAcceso in the schema.
        /// </summary>
        public virtual int CveControlAcceso
        {
            get;
            set;
        }

        /// <summary>
        /// There are no comments for CveControlAcceso in the schema.
        /// </summary>
        public virtual System.Nullable<DateTime> FechaUltimaConexion
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for IdControl in the schema.
        /// </summary>
        public virtual int IdControl
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Nombre in the schema.
        /// </summary>
        public virtual string Nombre
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for DireccionIp in the schema.
        /// </summary>
        public virtual string DireccionIp
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Puerto in the schema.
        /// </summary>
        public virtual System.Nullable<short> Puerto
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for FechaAlta in the schema.
        /// </summary>
        public virtual System.DateTime FechaAlta
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Marca in the schema.
        /// </summary>
        public virtual string Marca
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Modelo in the schema.
        /// </summary>
        public virtual string Modelo
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for VersionFirmware in the schema.
        /// </summary>
        public virtual string VersionFirmware
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for CapacidadHuellas in the schema.
        /// </summary>
        public virtual System.Nullable<int> CapacidadHuellas
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for FechaAdquisicion in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> FechaAdquisicion
        {
            get;
            set;
        }



        /// <summary>
        /// There are no comments for Habilitado in the schema.
        /// </summary>
        public virtual System.Nullable<bool> Activo
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Habilitado in the schema.
        /// </summary>
        public virtual System.Nullable<bool> Habilitado
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for FechaModificacion in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> FechaModificacion
        {
            get;
            set;
        }



        /// <summary>
        /// There are no comments for Oficina in the schema.
        /// </summary>
        public virtual Oficina Oficina
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Usuario_cve_usuario_alta in the schema.
        /// </summary>
        public virtual Usuario Usuario_cve_usuario_alta
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Usuario_modificado_por in the schema.
        /// </summary>
        public virtual Usuario Usuario_modificado_por
        {
            get;
            set;
        }




        /// <summary>
        /// There are no comments for EmpleadoControlAcceso in the schema.
        /// </summary>
        public virtual EmpleadoControlAcceso EmpleadoControlAcceso
        {
            get;
            set;
        }

    }

}
