//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asistencia.HuellaDactilar {
    
    
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://.com/WEBSERVICES/ECCMEX/RegistrosJornadasHuellaDactilar", ConfigurationName="HuellaDactilar.SI_OA_RegistroHuellaDactilar")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_OA_RegistroHuellaDactilar {
        
        // CODEGEN: Generating message contract since the operation SI_OA_RegistroHuellaDactilar is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://sap.com/xi/WebService/soap1.1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SI_OA_RegistroHuellaDactilar(Asistencia.HuellaDactilar.SI_OA_RegistroHuellaDactilar1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://sap.com/xi/WebService/soap1.1")]
        System.Threading.Tasks.Task SI_OA_RegistroHuellaDactilarAsync(Asistencia.HuellaDactilar.SI_OA_RegistroHuellaDactilar1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://.com/WEBSERVICES/ECCMEX/RegistrosJornadasHuellaDactilar")]
    public partial class DT_RegistroHuellaData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eVENT_IDField;
        
        private string eVENT_TYPE_IDField;
        
        private string mESSGE_TYPEField;
        
        private string oRIG_TIMEField;
        
        private string dRIVE_IDField;
        
        private string pLANT_IDField;
        
        private string dAY_EVENTField;
        
        private string vENDOR_IDField;
        
        private string rECEIVER_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EVENT_ID {
            get {
                return this.eVENT_IDField;
            }
            set {
                this.eVENT_IDField = value;
                this.RaisePropertyChanged("EVENT_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string EVENT_TYPE_ID {
            get {
                return this.eVENT_TYPE_IDField;
            }
            set {
                this.eVENT_TYPE_IDField = value;
                this.RaisePropertyChanged("EVENT_TYPE_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MESSGE_TYPE {
            get {
                return this.mESSGE_TYPEField;
            }
            set {
                this.mESSGE_TYPEField = value;
                this.RaisePropertyChanged("MESSGE_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ORIG_TIME {
            get {
                return this.oRIG_TIMEField;
            }
            set {
                this.oRIG_TIMEField = value;
                this.RaisePropertyChanged("ORIG_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DRIVE_ID {
            get {
                return this.dRIVE_IDField;
            }
            set {
                this.dRIVE_IDField = value;
                this.RaisePropertyChanged("DRIVE_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string PLANT_ID {
            get {
                return this.pLANT_IDField;
            }
            set {
                this.pLANT_IDField = value;
                this.RaisePropertyChanged("PLANT_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string DAY_EVENT {
            get {
                return this.dAY_EVENTField;
            }
            set {
                this.dAY_EVENTField = value;
                this.RaisePropertyChanged("DAY_EVENT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string VENDOR_ID {
            get {
                return this.vENDOR_IDField;
            }
            set {
                this.vENDOR_IDField = value;
                this.RaisePropertyChanged("VENDOR_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string RECEIVER_ID {
            get {
                return this.rECEIVER_IDField;
            }
            set {
                this.rECEIVER_IDField = value;
                this.RaisePropertyChanged("RECEIVER_ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_OA_RegistroHuellaDactilar1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://.com/WEBSERVICES/ECCMEX/RegistrosJornadasHuellaDactilar", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Asistencia.HuellaDactilar.DT_RegistroHuellaData[] MT_RegistroHuella;
        
        public SI_OA_RegistroHuellaDactilar1() {
        }
        
        public SI_OA_RegistroHuellaDactilar1(Asistencia.HuellaDactilar.DT_RegistroHuellaData[] MT_RegistroHuella) {
            this.MT_RegistroHuella = MT_RegistroHuella;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_OA_RegistroHuellaDactilarChannel : Asistencia.HuellaDactilar.SI_OA_RegistroHuellaDactilar, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_OA_RegistroHuellaDactilarClient : System.ServiceModel.ClientBase<Asistencia.HuellaDactilar.SI_OA_RegistroHuellaDactilar>, Asistencia.HuellaDactilar.SI_OA_RegistroHuellaDactilar {
        
        public SI_OA_RegistroHuellaDactilarClient() {
        }
        
        public SI_OA_RegistroHuellaDactilarClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_OA_RegistroHuellaDactilarClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_OA_RegistroHuellaDactilarClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_OA_RegistroHuellaDactilarClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Asistencia.HuellaDactilar.SI_OA_RegistroHuellaDactilar.SI_OA_RegistroHuellaDactilar(Asistencia.HuellaDactilar.SI_OA_RegistroHuellaDactilar1 request) {
            base.Channel.SI_OA_RegistroHuellaDactilar(request);
        }
        
        public void SI_OA_RegistroHuellaDactilar(Asistencia.HuellaDactilar.DT_RegistroHuellaData[] MT_RegistroHuella) {
            Asistencia.HuellaDactilar.SI_OA_RegistroHuellaDactilar1 inValue = new Asistencia.HuellaDactilar.SI_OA_RegistroHuellaDactilar1();
            inValue.MT_RegistroHuella = MT_RegistroHuella;
            ((Asistencia.HuellaDactilar.SI_OA_RegistroHuellaDactilar)(this)).SI_OA_RegistroHuellaDactilar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task Asistencia.HuellaDactilar.SI_OA_RegistroHuellaDactilar.SI_OA_RegistroHuellaDactilarAsync(Asistencia.HuellaDactilar.SI_OA_RegistroHuellaDactilar1 request) {
            return base.Channel.SI_OA_RegistroHuellaDactilarAsync(request);
        }
        
        public System.Threading.Tasks.Task SI_OA_RegistroHuellaDactilarAsync(Asistencia.HuellaDactilar.DT_RegistroHuellaData[] MT_RegistroHuella) {
            Asistencia.HuellaDactilar.SI_OA_RegistroHuellaDactilar1 inValue = new Asistencia.HuellaDactilar.SI_OA_RegistroHuellaDactilar1();
            inValue.MT_RegistroHuella = MT_RegistroHuella;
            return ((Asistencia.HuellaDactilar.SI_OA_RegistroHuellaDactilar)(this)).SI_OA_RegistroHuellaDactilarAsync(inValue);
        }
    }
}
